server:
    port: 80
eureka:
    instance:
        instance-id: consumer-order80
    client:
        service-url:
          defaultZone:
              http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
spring:
    application:
        name: cloud-consumer-application
