server:
    port: 8003
eureka:
    instance:
        instance-id: consumer-8003
    client:
        service-url:
            defaultZone:
                http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka


spring:
    application:
        name: consumer-8003
    rabbitmq:
        host: 190.160.9.100
        port: 5672
        username: itbaizhan
        password: itbaizhan
    cloud:
        function:
            definition: mybroadcast;myGroup
        stream:
            bindings:
                myBroadcast-in-0:
                    destination: my-broadcast-topic
                myGroup-in-0:
                    destination: my-group-topic
                    group: my-group-1
