server:
    port: 8001
eureka:
    instance:
        instance-id: provider-payment8001
    client:
        service-url:
          defaultZone:
              http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
spring:
    application:
        name: cloud-payment-provider
    sleuth:
        sampler:
            probability: 1.0
            rate: 100
logging:
    level:
        org.springframework.cloud.openfeign: debug
        org.springframework.cloud.sleuth: debug
