server:
    port: 8002
eureka:
    instance:
        instance-id: provider-payment8002
    client:
        service-url:
          defaultZone:
              http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
spring:
    application:
        name: cloud-payment-provider
