server:
    port: 80
eureka:
    instance:
        instance-id: consumer-feign-order80
    client:
        service-url:
            defaultZone:
                http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
spring:
    application:
        name: cloud-consumer-feign-application

logging:
    level:
        com.more.cloud.service: debug

feign:
    client:
        config:
          default:
              connect-timeout: 2000
              read-timeout: 2000

